### ISSUE TITLE
Light brightness icon

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-x-icons#107]
Brightness applet (XFCE) icon is from gnome and doesn't look minty
![- 04 05 2015 - 23 10 57](https://cloud.githubusercontent.com/assets/7345761/7461471/3cdb0d94-f2b3-11e4-89c6-b6424e203784.png)

**Comment by JosephMcc** [comment]
Do you by chance know the specific name of the icon being used?

**Comment by Yanpas** [comment]
/usr/share/icons/hicolor/48x48/status/xfpm-brightness-lcd.png

Suggesting this icon https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce/panel/22/xfpm-brightness-lcd.svg

**Comment by Yanpas** [comment]
XFCE by default reads it from Mint-X/panel/<number>/<icon.png>, but nothing happens when I place it in the folder and run update-icon-cache. Wrote elementary-xfce-dark in file index.theme - and voila it has appeared!

**Comment by JosephMcc** [comment]
It would be fairly easy to create a new dark version of the icon or just link to another suitable one that already exists in the theme. The problem is that it's then broken for people who use a dark panel. The one in your screenshot, while inconsistent with the others is at least readable on both light and dark panels.

**Comment by Yanpas** [comment]
Mint uses one icon theme both for light and dark panel? The dark panel as far as I remeber is used in Cinnamon only. So what may I draw? Dark with light borders or light with dark borders?

**Comment by Yanpas** [comment]
Currently xfce 4.12 ships new poer pluigin, so ot's not so critical for xfce, but it may be for Mate
